android {
    defaultConfig {
        // Ваши стандартные настройки, если они тут нужны, но для Gradle достаточно базового блока
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
